table _Measures
	lineageTag: 3ca1f626-22ce-4e47-8769-c5820dcf96fe

	measure 1_Total_Quantity = SUM(vw_fact_orders_enriched[sold_quantity])
		formatString: 0
		lineageTag: befa0c3e-cc9b-476e-92f6-5a880ca35265

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

